GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/65ae53ee7f24c6652c3230b

###

DELETE http://localhost:3001/api/persons/2

### 

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Jesse H",
  "number": "444444"
}