GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/65ae53ee7f24c6652c3230be

###

DELETE http://localhost:3001/api/persons/insert_id

### 

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Matias Z",
  "number": "123-99-9999"
}

###

GET http://localhost:3001/random